### ISSUE TITLE
Understanding Failed "3-year" chunk Scenario

### ISSUE THREAD

**Issue by bettinardi** [pbsag/tlumip#48]
When ODOT attempted to build a run where NED inputs “chunked” into the model in 3-year aggregate chunks (one year represented 3 years of economic growth), AA crashed and died with the error message below.  We need to understand why AA failed and if there is a way to allow for this type of scenario to be run in SWIM.  As context, the test was run to try and see if running AA less frequently (only running with a transport model skim adjust), would help produce more stable land use results, as AA seemed to oscillate greatly in-between transport years.  Alex wanted to see if limiting the number of times AA ran (since AA is deterministic) would help smooth the results.

A lot of these and ultimately the final one:

``` sh
14-Jul-2016 03:05, INFO, 14-Jul-2016 03:05, ERROR, Alt TechnologyOption cluster92 has utility NaN
14-Jul-2016 03:05, INFO, 14-Jul-2016 03:05, ERROR, Alt TechnologyOption cluster93 has utility NaN
14-Jul-2016 03:05, INFO, 14-Jul-2016 03:05, ERROR, Alt TechnologyOption cluster94 has utility NaN
14-Jul-2016 03:05, INFO, 14-Jul-2016 03:05, ERROR, Alt TechnologyOption cluster95 has utility NaN
14-Jul-2016 03:05, INFO, 14-Jul-2016 03:05, ERROR, Alt TechnologyOption cluster96 has utility NaN
14-Jul-2016 03:05, INFO, 14-Jul-2016 03:05, ERROR, Alt TechnologyOption cluster97 has utility NaN
14-Jul-2016 03:05, INFO, 14-Jul-2016 03:05, ERROR, Alt TechnologyOption cluster98 has utility NaN
14-Jul-2016 03:05, INFO, 14-Jul-2016 03:05, ERROR, Alt TechnologyOption cluster99 has utility NaN
14-Jul-2016 03:05, INFO, 14-Jul-2016 03:05, ERROR, Alt TechnologyOption EV has utility NaN
14-Jul-2016 03:05, INFO, 14-Jul-2016 03:05, ERROR, composite utility is positive infinity for BuyingZUtilityPECASZone:4138 Health Services
14-Jul-2016 03:05, INFO, 14-Jul-2016 03:05, ERROR, individual exchange utilities: 1:4.301702362084869 17:4.293679818333645 19:4.243442361695099
…
4136:5.269746462769304 4137:6.36678307454624 4138:7.097827128933841 4140:4.126656469521074 4141:3.7494643663188953 6001:-0.9330279690052015 6002:-7.69344207474034 6003:-7.926519635588867 6004:-4.512741549028708 6005:-0.44283650983086886 6006:1.0562993035685375
14-Jul-2016 03:05, INFO, 14-Jul-2016 03:05, INFO,              ActivitySummary.csv has been written
14-Jul-2016 03:05, INFO, 14-Jul-2016 03:05, INFO, Writing buying/selling matrices, PctIntrazonalxCommodityxBzone.csv and Histograms.csv
14-Jul-2016 03:05, INFO, 14-Jul-2016 03:05, WARN, Using default value of false for property aa.omxMatrices
14-Jul-2016 03:06, INFO, 14-Jul-2016 03:06, INFO, All Buying and Selling Flow matrices have been written
14-Jul-2016 03:06, INFO, 14-Jul-2016 03:06, INFO,              All buying and selling flow matrices have been written
14-Jul-2016 03:06, INFO, 14-Jul-2016 03:06, INFO,              Histograms.csv has been written
14-Jul-2016 03:06, INFO, 14-Jul-2016 03:06, INFO,              PctIntrazonalxCommodityxBzone.csv has been written
14-Jul-2016 03:06, INFO, 14-Jul-2016 03:06, INFO, Writing labor consumption and production
14-Jul-2016 03:06, INFO, 14-Jul-2016 03:06, INFO, Output has been written. Time in seconds: 67.097
14-Jul-2016 03:06, INFO, Finishing AA Model.
14-Jul-2016 03:06, INFO, Num alpha zones: 2986
14-Jul-2016 03:06, INFO, Max alpha zone: 4157
14-Jul-2016 03:06, INFO, Start of SPG2

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                at java.util.ArrayList.rangeCheck(ArrayList.java:604)
                at java.util.ArrayList.get(ArrayList.java:382)
                at com.pb.common.datafile.OLD_CSVFileReader.makeTableDataSet(OLD_CSVFileReader.java:676)
                at com.pb.common.datafile.OLD_CSVFileReader.readFile(OLD_CSVFileReader.java:288)
                at com.pb.common.datafile.OLD_CSVFileReader.readFile(OLD_CSVFileReader.java:237)
                at com.pb.common.datafile.OLD_CSVFileReader.readFile(OLD_CSVFileReader.java:75)
                at com.pb.models.synpop.SPG.readPiIncomeSizeHHs(SPG.java:3525)
                at com.pb.models.synpop.SPG.setupSpg2(SPG.java:1007)
                at com.pb.models.synpop.SPG.spg2(SPG.java:794)
                at com.pb.tlumip.ao.ModelEntry.runSpg2(ModelEntry.java:192)
                at com.pb.tlumip.ao.ModelEntry.main(ModelEntry.java:331)
```

**Comment by gregmacfarlane** [comment]
This is probably not an essential element of SWIM's design, so won't fix
